In [1]:
# =============================================================================
# Project Setup
# =============================================================================

from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("Project Root:", PROJECT_ROOT)

Project Root: d:\technology\Diploma\upgrad\May-2025-Batch\capstone-project\CreditCardFraudAI

In [2]:
pip install xgboost

Requirement already satisfied: xgboost in d:\technology\python\anaconda_installation\lib\site-packages (3.3.0)
Requirement already satisfied: numpy in d:\technology\python\anaconda_installation\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in d:\technology\python\anaconda_installation\lib\site-packages (from xgboost) (1.13.1)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~yspark (d:\technology\python\anaconda_installation\Lib\site-packages)
WARNING: Ignoring invalid distribution ~yspark (d:\technology\python\anaconda_installation\Lib\site-packages)
WARNING: Ignoring invalid distribution ~yspark (d:\technology\python\anaconda_installation\Lib\site-packages)

In [3]:
from src.models.model_factory import ModelFactory
factory = ModelFactory()

print(factory.available_models())

['decision_tree', 'logistic_regression', 'random_forest', 'xgboost']

In [4]:
from src.data.loader import DataLoader
from src.preprocessing.preprocessing_pipeline import (
    PreprocessingPipeline,
)
from src.models.model_factory import ModelFactory
from src.models.model_trainer import ModelTrainer

In [5]:
loader = DataLoader()

df = loader.load()

pipeline = PreprocessingPipeline()

X_train, X_test, y_train, y_test = pipeline.run(df)

2026-07-12 12:16:20 | INFO     | CreditCardFraudAI | Validating dataset path.
2026-07-12 12:16:20 | INFO     | CreditCardFraudAI | Loading dataset from D:\technology\Diploma\upgrad\May-2025-Batch\capstone-project\CreditCardFraudAI\data\raw\creditcard.csv
2026-07-12 12:16:23 | INFO     | CreditCardFraudAI | Dataset loaded successfully.
2026-07-12 12:16:23 | INFO     | CreditCardFraudAI | Rows: 284807 | Columns: 31
2026-07-12 12:16:23 | INFO     | CreditCardFraudAI | Starting preprocessing pipeline.
2026-07-12 12:16:23 | INFO     | CreditCardFraudAI | Applying missing value strategy: ignore
2026-07-12 12:16:23 | INFO     | CreditCardFraudAI | Removing duplicate rows.
2026-07-12 12:16:24 | INFO     | CreditCardFraudAI | Splitting dataset into train and test.
2026-07-12 12:16:25 | INFO     | CreditCardFraudAI | Train Shape : (226980, 30)
2026-07-12 12:16:25 | INFO     | CreditCardFraudAI | Test Shape : (56746, 30)
2026-07-12 12:16:25 | INFO     | CreditCardFraudAI | Applying imbalance strategy: smote
2026-07-12 12:16:26 | INFO     | CreditCardFraudAI | Original Shape : (226980, 30)
2026-07-12 12:16:26 | INFO     | CreditCardFraudAI | Resampled Shape : (453204, 30)
2026-07-12 12:16:26 | INFO     | CreditCardFraudAI | Preprocessing pipeline completed.

In [6]:
factory = ModelFactory()

rf = factory.get_model("random_forest")

trainer = ModelTrainer()

trained_model = trainer.train(
    rf,
    X_train,
    y_train,
)

print(trainer.summary())

2026-07-12 12:16:26 | INFO     | CreditCardFraudAI | Training model: RandomForestClassifier
2026-07-12 12:21:38 | INFO     | CreditCardFraudAI | Training completed in 312.233 seconds.

{'model_name': 'RandomForestClassifier', 'training_time_seconds': 312.233, 'training_timestamp': '2026-07-12T12:21:38.441186', 'training_samples': 453204, 'feature_count': 30}

In [7]:
from src.models.model_factory import ModelFactory
from src.models.model_trainer import ModelTrainer

# Initialize Factory and Trainer
factory = ModelFactory()
trainer = ModelTrainer()

# Models to train
models = [
    "logistic_regression",
    "decision_tree",
    "random_forest",
    "xgboost",
]

trained_models = {}
training_summary = []

for model_name in models:

    print("=" * 70)
    print(f"Training: {model_name}")

    # Create model
    model = factory.get_model(model_name)

    # Train model
    trained_model = trainer.train(
        model,
        X_train,
        y_train,
    )

    # Store trained model
    trained_models[model_name] = trained_model

    # Store metadata
    metadata = trainer.summary().copy()
    training_summary.append(metadata)

    print(metadata)
    print()

2026-07-12 12:21:38 | INFO     | CreditCardFraudAI | Training model: LogisticRegression

======================================================================
Training: logistic_regression

2026-07-12 12:21:40 | INFO     | CreditCardFraudAI | Training completed in 2.224 seconds.
2026-07-12 12:21:40 | INFO     | CreditCardFraudAI | Training model: DecisionTreeClassifier

{'model_name': 'LogisticRegression', 'training_time_seconds': 2.224, 'training_timestamp': '2026-07-12T12:21:40.711432', 'training_samples': 453204, 'feature_count': 30}

======================================================================
Training: decision_tree

2026-07-12 12:22:38 | INFO     | CreditCardFraudAI | Training completed in 58.055 seconds.
2026-07-12 12:22:38 | INFO     | CreditCardFraudAI | Training model: RandomForestClassifier

{'model_name': 'DecisionTreeClassifier', 'training_time_seconds': 58.055, 'training_timestamp': '2026-07-12T12:22:38.772517', 'training_samples': 453204, 'feature_count': 30}

======================================================================
Training: random_forest

2026-07-12 12:27:43 | INFO     | CreditCardFraudAI | Training completed in 304.282 seconds.
2026-07-12 12:27:43 | INFO     | CreditCardFraudAI | Training model: XGBClassifier

{'model_name': 'RandomForestClassifier', 'training_time_seconds': 304.282, 'training_timestamp': '2026-07-12T12:27:43.059509', 'training_samples': 453204, 'feature_count': 30}

======================================================================
Training: xgboost

d:\technology\python\anaconda_installation\Lib\site-packages\xgboost\training.py:200: UserWarning: [12:27:43] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2026-07-12 12:27:54 | INFO     | CreditCardFraudAI | Training completed in 11.407 seconds.

{'model_name': 'XGBClassifier', 'training_time_seconds': 11.407, 'training_timestamp': '2026-07-12T12:27:54.471933', 'training_samples': 453204, 'feature_count': 30}

In [8]:
import pandas as pd

training_summary_df = pd.DataFrame(training_summary)

training_summary_df

,model_name,training_time_seconds,training_timestamp,training_samples,feature_count
0,LogisticRegression,2.224,2026-07-12T12:21:40.711432,453204,30
1,DecisionTreeClassifier,58.055,2026-07-12T12:22:38.772517,453204,30
2,RandomForestClassifier,304.282,2026-07-12T12:27:43.059509,453204,30
3,XGBClassifier,11.407,2026-07-12T12:27:54.471933,453204,30

In [9]:
from src.evaluation.model_evaluator import ModelEvaluator

evaluator = ModelEvaluator()

evaluation_results = []

for name, model in trained_models.items():

    report = evaluator.evaluate(
        model,
        X_test,
        y_test,
    )

    evaluation_results.append(report)

    print("=" * 70)
    print(name)
    print("=" * 70)

    print(f"Accuracy : {report['accuracy']:.6f}")
    print(f"Precision: {report['precision']:.6f}")
    print(f"Recall   : {report['recall']:.6f}")
    print(f"F1 Score : {report['f1_score']:.6f}")
    print(f"ROC AUC  : {report['roc_auc']:.6f}")

    print()

2026-07-12 12:27:54 | INFO     | CreditCardFraudAI | Evaluating model: LogisticRegression
2026-07-12 12:27:55 | INFO     | CreditCardFraudAI | Evaluating model: DecisionTreeClassifier

======================================================================
logistic_regression
======================================================================
Accuracy : 0.973566
Precision: 0.052833
Recall   : 0.873684
F1 Score : 0.099640
ROC AUC  : 0.962667

2026-07-12 12:27:55 | INFO     | CreditCardFraudAI | Evaluating model: RandomForestClassifier

======================================================================
decision_tree
======================================================================
Accuracy : 0.997163
Precision: 0.326316
Recall   : 0.652632
F1 Score : 0.435088
ROC AUC  : 0.825186

2026-07-12 12:27:56 | INFO     | CreditCardFraudAI | Evaluating model: XGBClassifier

======================================================================
random_forest
======================================================================
Accuracy : 0.999454
Precision: 0.910256
Recall   : 0.747368
F1 Score : 0.820809
ROC AUC  : 0.958222

======================================================================
xgboost
======================================================================
Accuracy : 0.999066
Precision: 0.687500
Recall   : 0.810526
F1 Score : 0.743961
ROC AUC  : 0.968807

In [10]:
import pandas as pd

comparison_df = pd.DataFrame([
    {
        "Model": r["model_name"],
        "Accuracy": r["accuracy"],
        "Precision": r["precision"],
        "Recall": r["recall"],
        "F1 Score": r["f1_score"],
        "ROC AUC": r["roc_auc"],
    }
    for r in evaluation_results
])

comparison_df.sort_values(
    by="F1 Score",
    ascending=False,
)

                    Model  Accuracy  Precision    Recall  F1 Score   ROC AUC
2  RandomForestClassifier  0.999454   0.910256  0.747368  0.820809  0.958222
3           XGBClassifier  0.999066   0.687500  0.810526  0.743961  0.968807
1  DecisionTreeClassifier  0.997163   0.326316  0.652632  0.435088  0.825186
0      LogisticRegression  0.973566   0.052833  0.873684  0.099640  0.962667

In [11]:
from src.evaluation.model_comparison import ModelComparison

comparison = ModelComparison()

comparison_df = comparison.compare(
    evaluation_results
)

comparison_df

                    Model  Accuracy  Precision    Recall  F1 Score   ROC AUC
0  RandomForestClassifier  0.999454   0.910256  0.747368  0.820809  0.958222
1           XGBClassifier  0.999066   0.687500  0.810526  0.743961  0.968807
2  DecisionTreeClassifier  0.997163   0.326316  0.652632  0.435088  0.825186
3      LogisticRegression  0.973566   0.052833  0.873684  0.099640  0.962667

In [12]:
best = comparison.best_model(
    comparison_df
)

print(best)

{'Model': 'RandomForestClassifier', 'Accuracy': 0.9994537059880872, 'Precision': 0.9102564102564102, 'Recall': 0.7473684210526316, 'F1 Score': 0.8208092485549133, 'ROC AUC': 0.958222319669184}

In [13]:
ranking = comparison.rank_models(
    comparison_df
)

ranking

,Rank,Model,Accuracy,Precision,Recall,F1 Score,ROC AUC
0,1,RandomForestClassifier,0.999454,0.910256,0.747368,0.820809,0.958222
1,2,XGBClassifier,0.999066,0.687500,0.810526,0.743961,0.968807
2,3,DecisionTreeClassifier,0.997163,0.326316,0.652632,0.435088,0.825186
3,4,LogisticRegression,0.973566,0.052833,0.873684,0.099640,0.962667

In [14]:
comparison.summary(
    comparison_df
)

{'total_models': 4,
 'best_model': 'RandomForestClassifier',
 'best_f1_score': 0.8208092485549133,
 'best_roc_auc': 0.9688071655724012}

In [15]:
comparison.best_model(
    comparison_df,
    metric="ROC AUC",
)

comparison.rank_models(
    comparison_df,
    metric="Recall",
)

,Rank,Model,Accuracy,Precision,Recall,F1 Score,ROC AUC
0,1,LogisticRegression,0.973566,0.052833,0.873684,0.099640,0.962667
1,2,XGBClassifier,0.999066,0.687500,0.810526,0.743961,0.968807
2,3,RandomForestClassifier,0.999454,0.910256,0.747368,0.820809,0.958222
3,4,DecisionTreeClassifier,0.997163,0.326316,0.652632,0.435088,0.825186

In [16]:
from src.evaluation.model_registry import ModelRegistry

registry = ModelRegistry()

for model_name, trained_model, metadata in zip(
    trained_models.keys(),
    trained_models.values(),
    trainer.history(),
):

    registry.save_model(
        trained_model,
        metadata,
    )

print(registry.list_models())

2026-07-12 12:27:57 | INFO     | CreditCardFraudAI | Saving model: LogisticRegression
2026-07-12 12:27:57 | INFO     | CreditCardFraudAI | Model saved successfully.
2026-07-12 12:27:57 | INFO     | CreditCardFraudAI | Saving model: DecisionTreeClassifier
2026-07-12 12:27:57 | INFO     | CreditCardFraudAI | Model saved successfully.
2026-07-12 12:27:57 | INFO     | CreditCardFraudAI | Saving model: RandomForestClassifier

2026-07-12 12:27:57 | INFO     | CreditCardFraudAI | Model saved successfully.
2026-07-12 12:27:57 | INFO     | CreditCardFraudAI | Saving model: XGBClassifier
2026-07-12 12:27:57 | INFO     | CreditCardFraudAI | Model saved successfully.

['DecisionTreeClassifier', 'LogisticRegression', 'RandomForestClassifier', 'XGBClassifier']

In [17]:
loaded_model = registry.load_model(
    "RandomForestClassifier"
)

print(type(loaded_model).__name__)

2026-07-12 12:27:57 | INFO     | CreditCardFraudAI | Loading model: RandomForestClassifier

RandomForestClassifier

In [18]:
metadata = registry.load_metadata(
    "RandomForestClassifier"
)

metadata

{'model_name': 'RandomForestClassifier',
 'training_time_seconds': 304.282,
 'training_timestamp': '2026-07-12T12:27:43.059509',
 'training_samples': 453204,
 'feature_count': 30,
 'saved_timestamp': '2026-07-12T12:27:57.257377',
 'model_path': 'D:\\technology\\Diploma\\upgrad\\May-2025-Batch\\capstone-project\\CreditCardFraudAI\\models\\RandomForestClassifier.pkl'}